[package]
name = "gbas"
version = "0.1.0"
authors = ["Yaron Tausky <yaron.tausky@gmail.com>"]
description = "An assembler for Game Boy"
repository = "https://github.com/ytausky/gbas"
license = "GPL-3.0-or-later"

[dependencies]
